apiVersion: v1
kind: Service
metadata:
  name: opsight-ai-rca
  namespace: opsight
  labels:
    app: opsight-ai-rca
spec:
  selector:
    app: opsight-ai-rca
  ports:
    - name: http
      port: 8090
      targetPort: 8090
