apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ai-rca-deployment.yaml
  - ai-rca-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - dependency-deployment.yaml
  - dependency-service.yaml
  - hpa.yaml
  - ingress.yaml
  - networkpolicy.yaml
