apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: opsight-api-policy
  namespace: opsight
spec:
  podSelector:
    matchLabels:
      app: opsight-api
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: payment-gateway
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 4317
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
