apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../api
  - ../../monitoring
images:
  - name: opsight/api
    newTag: local
  - name: opsight/payment-gateway
    newTag: local
  - name: opsight/ai-rca
    newTag: local
