apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../api
  - ../../monitoring
namespace: opsight-dev
images:
  - name: opsight/api
    newTag: dev
  - name: opsight/payment-gateway
    newTag: dev
  - name: opsight/ai-rca
    newTag: dev
patchesJson6902:
  - target:
      version: v1
      kind: Namespace
      name: opsight
    patch: |-
      - op: replace
        path: /metadata/name
        value: opsight-dev
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: kube-state-metrics
    patch: |-
      - op: replace
        path: /metadata/name
        value: kube-state-metrics-opsight-dev
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: kube-state-metrics
    patch: |-
      - op: replace
        path: /metadata/name
        value: kube-state-metrics-opsight-dev
      - op: replace
        path: /roleRef/name
        value: kube-state-metrics-opsight-dev
patchesStrategicMerge:
  - environment-config.yaml
  - ingress.yaml
  - replicas.yaml
  - resources.yaml
