apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: opsight
  name: opsight-api
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: opsight
  name: payment-gateway
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: opsight
  name: opsight-ai-rca
spec:
  replicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: opsight
  name: opsight-api
spec:
  minReplicas: 2
  maxReplicas: 6
